config/routes.rb
TheBucketlist::Application.routes.draw do
  resources :tasks, only: ["index", "create", "show", "update", "destroy"]
  resources :sessions

  match "/home/splash" => 'home#splash', as:"/"
  
  match "login" => "sessions#new", as:"/login"
  match "logout" => "sessions#destroy", as:"/logout"

  root :to => 'home#splash'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :done, :name
  
  validates_presence_of :name
  before_create :mark_as_incomplete
  
  scope :all, order("tasks.created_at desc")
  scope :done, where("done = ?", true)
  scope :left, where("done = ?", false)
  
  def mark_as_incomplete
    self.done = false
    true # this method returns false otherwise :\
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :username
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  force_ssl

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # http_basic_authenticate_with :name => "vidur", :password => "goosefraba"
  
  def splash
    @tasks = Task.all
    @done_count = Task.done.size
    @left_count = Task.left.size
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { render partial: "/tasks/task" }
        # format.json { render json: @task, status: :ok }
      else
        format.html { redirect_to root_url }
        # format.json { render :nothing }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to root_url }
        # format.json { head :no_content }
      else
        format.html { redirect_to root_url }
        # format.json { head :no_content }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/splash.html.erb
<div id="views">
  <div id="list">
    <h1>The Bucket List</h1>

		<% if current_user %>
			<%= form_tag "/tasks", method: "post", remote:"true", id:"add_new_task" do %>
	      <input name="task[name]" type="text" placeholder="What needs to be done?">
			<% end %>
		<% end %>

    <div class="tasks">
			<% for task in @tasks %>
				<% if task.done %>
			  <div class="task done">
				<% else %>
			  <div class="task">
					<% if current_user %>
		      <input id="<%= task.id %>" class="marked_done" type="checkbox" value="true">
					<% end %>
				<% end %>
		      <span class="task_name"><%= task.name %></span>
					<% if current_user %>
						<a class="destroy" href="<%= task_path(task) %>" data-method="delete" data-remote="true"><%= image_tag("destroy.png") %></a>
					<% end %>
		
			  </div> <!-- End of Task -->
			<% end %>
		</div>

    <footer>
      <!-- <a class="clear">Clear completed</a> -->
      <div class="count left"><span id="count_left" class="countVal"><%= @left_count %></span> left</div>
      <div class="count done">done <span id="count_done" class="countVal"><%= @done_count %></span></div>
    </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vidur's Bucket List</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

	<div class="lock-icon">
		<% if current_user %>
			<a href="/logout"><%= image_tag("unlock.png") %></a>
		<% else %>
			<a id="login-link" data-toggle="modal" href="#login-form"><%= image_tag("lock.png") %></a>
		<% end %>
	</div>

	<div class="modal" id="login-form">
		<%= form_tag sessions_path do %>
		<div class="form-row">
			<%= text_field_tag :username, params[:username], id:"username" %>
		</div>
		<div class="form-row">
			<%= password_field_tag :password, params[:password] %>
		</div>
		<div class="form-row">
			<%= submit_tag "Log In", class:"btn" %>
		</div>
		<% end %>
	</div>
</body>
</html>

app/views/tasks/_task.html.erb
<div class='task'>  <input id='<%= @task.id %>' class='marked_done' type='checkbox' value='true'>  <span><%= @task.name %></span>	<a class='destroy' href='<%= task_path(@task) %>' data-method='delete' data-remote='true'><%= image_tag('destroy.png') %></a></div>